MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"
# Este bloque toma una tabla de variantes en GH y resume.
%.summary.tsv:Q: %.tsv
	echo "[DEBUG] making summary of $prereq file"
	Rscript --vanilla summarizer.R $prereq $target.build \
	&& mv $target.build $target
