MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"

##This code block will filter rows where the column "GeneHancer_type"
# aka the column number 77 have a value that begins with "^GH"

%.filtered.tsv:Q: %.tsv.gz
	echo "[DEBUG] filtering GeneHancer variants for $prereq"
	zcat $prereq \
	|awk '
		BEGIN {FS=OFS="\t"}
		NR == 1 {print $0} 
		$77~/^GH.*/ { print $0 }
	' > $target.build \
	&& mv $target.build $target
